# --- Server ---
server.port=8081

# --- Oracle Database Configuration ---
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=placement_prep
spring.datasource.password=placement123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# --- Hibernate / JPA ---
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
openai.api.key=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
admin.password=admin123